<a href="https://colab.research.google.com/github/roseleen-kaur/DataAnalytics_2022_Summer/blob/main/NumpyHW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY HOMEWORK#
Roseleen Kaur

###Question 1###
Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays: 
```
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
```

Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.



In [132]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,8])

#finding distinct/ unique items
#https://www.geeksforgeeks.org/find-common-values-between-two-numpy-arrays/:~:text=In%20NumPy%2C%20we%20can%20find,the%20common%20elements%20will%20appear.
print(np.intersect1d(a, b))

[2 4]


### Question 2 ###
Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.

1   6    11

2   7    12

3   8    13

4   9    14

5   10   15



In [133]:
arr = np.arange(1,16).reshape(3,5)
print(f'Arr \n {arr.T}')

Arr 
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Question 3 ###
The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [134]:
arr2 = arr.flatten()
print(f'Arr2 \n {arr2}')

Arr2 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Question 4 ###
Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [136]:
new_arr = arr.reshape(3,1,5)
print(f'3-D Array \n {new_arr}')


3-D Array 
 [[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


### Question 5 ###
Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.



In [137]:
org_arr = new_arr.reshape(3,5) 
print(f'Back to the Original \n {org_arr.T}')

Back to the Original 
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


###Question 6###
You are given the following two arrays:
```
a = np.array([12, 5, 7, 15, 3, 1, 8])

b = np.array([14, 6, 3, 11, 19, 12, 5])
```
Write a Python/Numpy code block that removes from array a any items that are also present in array b.



In [139]:
a = np.array([12, 5, 7, 15, 3, 1, 8])

b = np.array([14, 6, 3, 11, 19, 12, 5])

#so here 3, 12, and 5 will disappear from array a
#https://stackoverflow.com/questions/10996140/how-to-remove-specific-elements-in-a-numpy-array
#this is where I got the np.setdiff1d from, it seemed like the best answer, 
#it removed the similar values.
new_a = np.setdiff1d(a,b)
print(f'Old a: {a}')
print(f'New a: {new_a}')
print(f'b:     {b}')


Old a: [12  5  7 15  3  1  8]
New a: [ 1  7  8 15]
b:     [14  6  3 11 19 12  5]


#DATA SET QUESTIONS #


### Question 7###
Answer the following questions about the accompanying data file.



In [140]:
#first read the file.
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/roseleen-kaur/DataAnalytics_2022_Summer/main/Module6_Data.csv')
df

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0   1979                 7102100.0                                    1512.0   
1   1980                 7071639.0                                    1506.0   
2   1981                 7089241.0                                    1309.0   
3   1982                 7109105.0                                    1382.0   
4   1983                 7181224.0                                    1424.0   
5   1984                 7234514.0                                    1465.0   
6   1985                 7274054.0                                    1326.0   
7   1986                 7319246.0                                    1351.0   
8   1987                 7342476.0                                    1447.0   
9   1988                 7353719.0                                    1484.0   
10  1989                 7344175.0                                    1402.0   
11  1990                 7335650.0                                    1424.0   
12  1991                 7374501.0                                    1469.0   
13  1992                 7428944.0                                    1369.0   
14  1993                 7506166.0                                    1368.5   
15  1994                 7570458.0                                    1357.7   
16  1995                 7633040.0                                    1325.7   
17  1996                 7697812.0                                    1297.9   
18  1997                 7773443.0                                    1205.5   
19  1998                 7858259.0                                    1219.5   
20  1999                 7947660.0                                    1237.2   
21  2000                 8008278.0                                    1240.4   
22  2001                 8024963.5                                    1184.0   
23  2002                 8041649.0                                    1135.6   
24  2003                 8058334.5                                    1093.7   
25  2004                 8075020.0                                    1099.5   
26  2005                 8091705.5                                    1138.0   
27  2006                 8108391.0                                    1069.0   
28  2007                 8125076.5                                    1114.0   
29  2008                 8141762.0                                    1098.0   
30  2009                 8158447.5                                    1007.5   
31  2010                 8175133.0                                    1039.0   
32  2011                 8284098.0                                    1021.0   
33  2012                 8361179.0                                    1009.1   
34  2013                 8422460.0                                    1006.1   
35  2014                 8471990.0                                     996.0   
36  2015                 8516502.0                                    1009.0   
37  2016                 8537673.0                                    1002.0   
38  2017                 8622698.0                                     990.2   

    Per Capita(Gallons per person per day)  
0                                      213  
1                                      213  
2                                      185  
3                                      194  
4                                      198  
5                                      203  
6                                      182  
7                                      185  
8                                      197  
9                                      202  
10                                     191  
11                                     194  
12                                     199  
13                                     184  
14                                     182  
15                                     179  
16                                    

### Question 7.1 ###
What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [142]:
#first we need to turn these into numpy arrays?
Year = df['Year'].values
Pop  = df['New York City Population'].values
nyc_consumption = df['NYC Consumption(Million gallons per day)'].values
Per_Capita = df['Per Capita(Gallons per person per day)'].values
print(f'Year\n{Year}')
print(f'Population\n{Pop}')
print(f'Consumption\n{nyc_consumption}')
print(f'Per Capita \n{Per_Capita}')



Year
[1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992
 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Population
[7102100.  7071639.  7089241.  7109105.  7181224.  7234514.  7274054.
 7319246.  7342476.  7353719.  7344175.  7335650.  7374501.  7428944.
 7506166.  7570458.  7633040.  7697812.  7773443.  7858259.  7947660.
 8008278.  8024963.5 8041649.  8058334.5 8075020.  8091705.5 8108391.
 8125076.5 8141762.  8158447.5 8175133.  8284098.  8361179.  8422460.
 8471990.  8516502.  8537673.  8622698. ]
Consumption
[1512.  1506.  1309.  1382.  1424.  1465.  1326.  1351.  1447.  1484.
 1402.  1424.  1469.  1369.  1368.5 1357.7 1325.7 1297.9 1205.5 1219.5
 1237.2 1240.4 1184.  1135.6 1093.7 1099.5 1138.  1069.  1114.  1098.
 1007.5 1039.  1021.  1009.1 1006.1  996.  1009.  1002.   990.2]
Per Capita 
[213 213 185 194 198 203 182 185 197 202 191 194 199 184 182 179 174 169
 155 155 156 155 148

In [143]:
#then we answer the question
max_yearly = np.max(nyc_consumption)
print(f'Maximum Yearly NYC Consumption: {max_yearly}')

Maximum Yearly NYC Consumption: 1512.0


###Question 7.2 ###
How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.

In [144]:
print(f'Total Years: {Year.shape}')

Total Years: (39,)


###Question 7.3 ###
What is the mean and the standard deviation of the per capita daily water consumption?

In [145]:
#first let's find the mean (average)
mean = np.average(Per_Capita)
print(f'Mean:{mean: .2f}')
# then let's do the standard deviation
std = np.std(Per_Capita)
print(f'Standard Deviation:{std: .2f}')

Mean: 160.31
Standard Deviation: 31.52


###Question 4###
What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [146]:
#this finds the differences
pop_diff = np.diff(Pop)
print(f'Population Inc/Dec \n{pop_diff}')
#just to check that there are actually 38 differences
#for 39 rows
#print(pop_diff.shape)

Population Inc/Dec 
[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
